const FETCH_USER = 'FETCH_USER';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const LOGOUT = 'LOGOUT';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const CATEGORY_PRODUCTS = 'CATEGORY_PRODUCTS'
const CATEGORIES = 'CATEGORIES'
const LATEST_PRODUCTS = 'LATEST_PRODUCTS';
const ALL_PRODUCTS = 'ALL_PRODUCTS';
const ADD_TO_CART = 'ADD_TO_CART';
const DELETE_FROM_CART = 'DELETE_FROM_CART';
const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
const TRANSACTION = 'TRANSACTION';
const CURRENT_PRODUCT = 'CURRENT_PRODUCT';
const LANGUAGE = 'LANGUAGE';
const GET_BRANDS = 'GET_BRANDS';
const SLIDER_IMAGES = 'SLIDER_IMAGES';
const CURRENT_CATEGORY = 'CURRENT_CATEGORY';
const WHISHLIST_ITEMS = 'WHISHLIST_ITEMS';



export {FETCH_USER, LOGIN, SIGNUP, LOGOUT, FETCH_PRODUCTS, CATEGORY_PRODUCTS, CATEGORIES, LATEST_PRODUCTS, ADD_TO_CART, DELETE_FROM_CART, UPDATE_CART_ITEM, TRANSACTION, ALL_PRODUCTS, CURRENT_PRODUCT, LANGUAGE, GET_BRANDS, SLIDER_IMAGES, CURRENT_CATEGORY, WHISHLIST_ITEMS};